#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

exec clojure \
     -A:nrepl:rebel \
     -i dev/init.clj \
     -e "(do (require 'advent.puzzle05) (in-ns 'advent.puzzle05) nil)" \
     -m rebel-readline.main \
     "$@"
